# fly.toml app configuration file generated for ordo-backend on 2025-03-10T09:46:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ordo-backend'
primary_region = 'lhr'

[build]

[env]
  NODE_ENV="production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
